adding a note to check ntp.txt
My customer is using NTP on SLE 15 ,, the ha.txt have always this  output: 
# chronyc sources -v
ERROR: Command not found or not executable
because we assume with SLE 15 people will use chrony not NTP ,, but also chrony can be used in SLE 12.. 
Since we collecting everything in good way in ntp.txt ,, let us not duplicate the code.